drop database library;
create database library character set utf8;

use library;

CREATE TABLE user
(
  id INT,
  email VARCHAR(50) UNIQUE,
  password VARCHAR(255) NOT NULL,
  firstname VARCHAR(50) NOT NULL,
  lastname VARCHAR(50) NOT NULL,
  dob DATE,
  photo VARCHAR(255),
  PRIMARY KEY (id)
) ENGINE=INNODB CHARACTER SET=utf8;

CREATE TABLE role
(
    id INT AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=INNODB CHARACTER SET=utf8;



CREATE TABLE author
(
  id INT AUTO_INCREMENT,
  firstname VARCHAR(50) NOT NULL,
  middlename VARCHAR(50),
  lastname VARCHAR(50) NOT NULL,
  dob DATE,
  PRIMARY KEY (id)

) ENGINE=INNODB CHARACTER SET=utf8;

CREATE TABLE genre
(
  id INT AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB CHARACTER SET=utf8;

CREATE TABLE publicity
(
  id INT AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB CHARACTER SET=utf8;

CREATE TABLE book
(
  id INT AUTO_INCREMENT,
  title VARCHAR(256) NOT NULL,
  annotation TEXT,
  published VARCHAR(4),
  publicity_id INT,
  pages INT,
  PRIMARY KEY (id),
  FOREIGN KEY (publicity_id) REFERENCES publicity (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=INNODB CHARACTER SET=utf8;

CREATE TABLE book_author
(
  book_id INTEGER NOT NULL,
  author_id INTEGER NOT NULL,
  FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=INNODB;

CREATE TABLE book_genre
(
  book_id INTEGER NOT NULL,
  genre_id INTEGER NOT NULL,
  FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=INNODB;

CREATE TABLE logbook
(
  book_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  handout DATE NOT NULL,
  returned DATE,
  FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=INNODB;

CREATE TABLE user_role
(
    user_id INTEGER NOT NULL,
    role_id INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=INNODB;

CREATE TABLE hibernate_sequence
(
  next_val INT
) ENGINE=INNODB;
